# Generated by Django 3.2.10 on 2022-01-03 05:13

from django.db import migrations, models
import django.db.models.deletion

try:
    import wagtail.blocks as blocks
    import wagtail.fields as fields
except ImportError:
    # Wagtail <5
    import wagtail.core.blocks as blocks
    import wagtail.core.fields as fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wagtailcore', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('body', fields.StreamField([('text', blocks.StructBlock([('body', blocks.RichTextBlock(required=False))], template='text_block.html')), ('section', blocks.StreamBlock([('text', blocks.StructBlock([('body', blocks.RichTextBlock(required=False))], template='text_block.html'))])), ('list', blocks.StructBlock([('title', blocks.TextBlock(required=False)), ('items', blocks.StreamBlock([('item', blocks.StructBlock([('body', blocks.RichTextBlock(required=False))], template='text_block.html'))]))]))], blank=True, null=True)),
            ],
            bases=('wagtailcore.page',),
        ),
    ]
